servers:
  - serverId: 0
    host: "server0"
    port: "8080"
  - serverId: 1
    host: "server1"
    port: "8080"
  - serverId: 2
    host: "server2"
    port: "8080"
  - serverId: 3
    host: "server3"
    port: "8080"
  - serverId: 4
    host: "server4"
    port: "8080"
  - serverId: 5
    host: "server5"
    port: "8080"
  - serverId: 6
    host: "server6"
    port: "8080"
  - serverId: 7
    host: "server7"
    port: "8080"
  - serverId: 8
    host: "server8"
    port: "8080"
  - serverId: 9
    host: "server9"
    port: "8080"
  - serverId: 10
    host: "server10"
    port: "8080"
  - serverId: 11
    host: "server11"
    port: "8080"
  - serverId: 12
    host: "server12"
    port: "8080"
  - serverId: 13
    host: "server13"
    port: "8080"
  - serverId: 14
    host: "server14"
    port: "8080"
  - serverId: 15
    host: "server15"
    port: "8080"