servers:
  - serverId: 0
    host: "server0"
    port: "8080"
  - serverId: 1
    host: "server1"
    port: "8080"
  - serverId: 2
    host: "server2"
    port: "8080"
  - serverId: 3
    host: "server3"
    port: "8080"
  - serverId: 4
    host: "server4"
    port: "8080"
  - serverId: 5
    host: "server5"
    port: "8080"
  - serverId: 6
    host: "server6"
    port: "8080"
  - serverId: 7
    host: "server7"
    port: "8080"